# Generated by Django 4.1.9 on 2023-10-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_friendship"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(fields=("from_user", "to_user"), name="unique_friendship"),
        ),
    ]
