# Generated by Django 4.1.9 on 2023-10-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_friendship_unique_friendship"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                check=models.Q(("from_user", models.F("to_user")), _negated=True), name="not_follow_myself"
            ),
        ),
    ]
