# Generated by Django 4.1.9 on 2023-10-28 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_friendship_not_follow_myself"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship",
            options={"ordering": ["-created_at"]},
        ),
    ]
