# Generated by Django 4.1.9 on 2023-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0002_rename_user_tweet_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="created_by",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=140),
        ),
    ]
